_target_: src.module.regression_model.utae_mf.UTAEMF
input_dim: 14
encoder_widths : [64, 64, 64, 128]
decoder_widths: [32, 32, 64, 128] #in concat coupling mode, the model already takes care of doubling the number of features
out_conv: [32,1]
str_conv_k: 4
str_conv_s: 2
str_conv_p : 1
agg_mode: "att_group"
encoder_norm: "group"
n_head: 16
d_model: 256
d_k: 4
pad_value: 0
padding_mode: "reflect"
last_relue: False
coupling_mode: concat