_target_: lightning.pytorch.trainer.Trainer
default_root_dir: ${log_dir}

min_epochs: 1
max_epochs: 100

accelerator: gpu
num_nodes: 1
strategy: auto
precision : 16-mixed
log_every_n_steps: 50
check_val_every_n_epoch: 1
profiler : null
