# model : h-sera_h_global_figures
model : d-sera_d_huber_loss
min_diff : -50
max_diff : 5
threshold_min_value : -5
thrashold_min_area : 50

resolution : 2.5  
real_patch_size_plot : 500
nb_jobs : 10
seed : 12345
date_column : lidar_acquisition_date
print_config : True
resampling_method_pred : mean
nb_plots : 50

data_dir : /lustre/fsn1/projects/rech/ego/uof45xi/data/
save_dir : ${data_dir}/logs/metrics/diff_map/${model}
output_path_xlsx : ${save_dir}/metrics_${model}.xlsx
grouping_dates : lidar_acquisition_date
version_prediction : test_diff_map
version_metrics : test_diff_map_global_figures

geometries_path : ${data_dir}/logs/pred_sera/${model}/${version_prediction}/predictions/predict_gdf.geojson
hydra:
  run:
    dir: ${save_dir}
  output_subdir : hydra_logs

get_images : 
  _target_ : src.postprocessing.metrics.get_images_utils.get_images
  image_loaded_set:    
    difference_pred : 
      _target_: src.postprocessing.metrics.get_images_utils.output_image_loader
      path: ${data_dir}/logs/pred_sera/${model}/${version_prediction}/predictions/data/${model}_full.vrt
      resolution: ${resolution}
      resampling_method: ${resampling_method_pred}
      scaling_factor: 1
      min_image: ${min_diff}
      max_image: ${max_diff}
      open_even_oob: False
      max_date: null
      min_date: null
      grouping_dates: null

    height_target_t1 : 
      _target_: src.postprocessing.metrics.get_images_utils.output_image_loader
      path: ${data_dir}/lidar/<year>/lidar.vrt
      resolution: ${resolution}
      resampling_method: max
      scaling_factor: 1
      min_image: null
      max_image: null
      open_even_oob: False
      max_date: null
      min_date: null
      grouping_dates: lidar_acquisition_date_t1

    height_target_t2 : 
      _target_: src.postprocessing.metrics.get_images_utils.output_image_loader
      path: ${data_dir}/lidar/<year>/lidar.vrt
      resolution: ${resolution}
      resampling_method: max
      scaling_factor: 1
      min_image: null
      max_image: null
      open_even_oob: False
      max_date: null
      min_date: null
      grouping_dates: lidar_acquisition_date_t2
      
  image_computed_set:

    difference_target :
      _target_: src.postprocessing.metrics.get_images_utils.difference_computer
      input_name_1: height_target_t1
      input_name_2: height_target_t2
      min_image: ${min_diff}
      max_image: ${max_diff}

get_metrics_local : 
  _target_: src.postprocessing.metrics.get_metrics_local_utils.get_metrics_local
  metrics_set :  
    flatten_target_pred :
      _target_: src.postprocessing.metrics.get_metrics_local_utils.flatten_local_computer
      name_pred : difference_pred
      name_target : difference_target

    flatten_target_pred_positive :
      _target_: src.postprocessing.metrics.get_metrics_local_utils.flatten_local_computer
      name_pred : difference_pred
      name_target : difference_target
      min_value_threshold_and: 0

    flatten_target_pred_negative :
      _target_: src.postprocessing.metrics.get_metrics_local_utils.flatten_local_computer
      name_pred : difference_pred
      name_target : difference_target
      max_value_threshold_and: ${threshold_min_value}


get_metrics_global : 
  _target_: src.postprocessing.metrics.get_metrics_global_utils.get_metrics_global
  metrics_to_print : null
  metrics_set :
    flatten_tuples_target_pred :
      _target_: src.postprocessing.metrics.get_metrics_global_utils.concat_tuples_global_computer
      name_metric : flatten_target_pred
    flatten_tuples_target_pred_positive :
      _target_: src.postprocessing.metrics.get_metrics_global_utils.concat_tuples_global_computer
      name_metric : flatten_target_pred_positive
    flatten_tuples_target_pred_negative :
      _target_: src.postprocessing.metrics.get_metrics_global_utils.concat_tuples_global_computer
      name_metric : flatten_target_pred_negative

get_plots_local: null

get_plots_global: 
  _target_: src.postprocessing.metrics.get_plots_global_utils.get_plots_global
  save_dir : ${save_dir}/${version_metrics}_figures
  model_name : ${model}
  plot_set :
    # scatter_plot_target_pred :
    #   _target_: src.postprocessing.metrics.get_plots_global_utils.plot_model
    #   nb_row: 1
    #   nb_col : 1
    #   size_plot_width: 5
    #   size_plot_height: 5
    #   graph_list :
    #     - _target_: src.postprocessing.metrics.get_plots_global_utils.graph_model
    #       idx_row : 0
    #       idx_col : 0
    #       graph_title : "Scatter Plot Target Pred"
    #       rowspan: 1
    #       colspan: 1
    #       method_graph:
    #         _target_: src.postprocessing.metrics.get_plots_global_utils.method_scatter_density
    #         metric_name: flatten_tuples_target_pred
    #         x_label: "Targets"
    #         y_label: "Predictions"
    #         min_range: ${min_diff}
    #         max_range: ${max_diff}
    #         bins: 30
    #         metrics_plot: ["r2"]
    #         max_points_on_scatter: 10000000
    #         point_size: 1
              # x_y_line: True
              # fit_line: False
              # show_legend: False


    scatter_plot_target_pred_positive :
      _target_: src.postprocessing.metrics.get_plots_global_utils.plot_model
      nb_row: 1
      nb_col : 1
      size_plot_width: 5
      size_plot_height: 5
      graph_list :
        - _target_: src.postprocessing.metrics.get_plots_global_utils.graph_model
          idx_row : 0
          idx_col : 0
          graph_title : "Scatter Plot Target Pred Positive"
          rowspan: 1
          colspan: 1
          method_graph:
            _target_: src.postprocessing.metrics.get_plots_global_utils.method_scatter_density
            metric_name: flatten_tuples_target_pred_positive
            x_label: "Targets"
            y_label: "Predictions"
            min_range: 0
            max_range: 5
            bins: 30
            metrics_plot: ["r2"]
            max_points_on_scatter: 1000000
            point_size: 1
            x_y_line: True
            fit_line: False
            show_legend: False
      
    scatter_plot_target_pred_negative :
      _target_: src.postprocessing.metrics.get_plots_global_utils.plot_model
      nb_row: 1
      nb_col : 1
      size_plot_width: 5
      size_plot_height: 5
      graph_list :
        - _target_: src.postprocessing.metrics.get_plots_global_utils.graph_model
          idx_row : 0
          idx_col : 0
          graph_title : "Scatter Plot Target Pred"
          rowspan: 1
          colspan: 1
          method_graph:
            _target_: src.postprocessing.metrics.get_plots_global_utils.method_scatter_density
            metric_name: flatten_tuples_target_pred_negative
            x_label: "Targets"
            y_label: "Predictions"
            min_range: -50
            max_range: -5
            bins: 30
            metrics_plot: ["r2"]
            max_points_on_scatter: 1000000
            point_size: 1
            x_y_line: True
            fit_line: False
            show_legend: False