defaults:
  - regression: UNet
  - _self_


instance:
  _target_: src.models.networks.ic_classic_network.ICClassicNetwork
  regression_model: ${model.network.regression}
  change_method : ${datamodule.dataset.method_change}
  use_final_layer : False