year: "both" # Can be "2021", "2022", or "both".
bbox: ??? # The bounding box for the area of interest: [min_lon, min_lat, max_lon, max_lat]. This is a required parameter.
output_dir: "./canopy_height_data" # The directory where the output files will be saved.
scale: 10 # The spatial resolution of the output image in meters.
crs: 'EPSG:3035' # The coordinate reference system for the output image (e.g., 'EPSG:3035' for Europe).
name: 'canopy_height' # The base name for the output file(s).
