root_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data/
data_dir: ${root_dir}/sentinel/composites/lidarhd
hydra:
  run :
    dir : ${data_dir}/logs
  output_subdir : hydra_logs

create_vrts: src.preprocessing.get_clean_dataset_utils.create_vrts_composites
get_valid_vrts: src.preprocessing.get_clean_dataset_utils.get_valid_vrts_composites

n_jobs_parrallelized: -1

initial_gdf_path: ${root_dir}/utils/gdf_height_map_initial.geojson
grouping_dates: lidar_acquisition_date
validation_column: valid_vrts
gdf_clean_path: ${data_dir}/gdf_height_map_composites.geojson
gdf_unclean_path: ${data_dir}/gdf_height_map_composites_unsaved.geojson
