root_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data/
gdf_path: ${root_dir}/utils/geometries.geojson
gdf_output_name: gdf_height_map_initial
columns_to_drop:
  - lidar_url
  - X
  - Y
  - n_lidar_points
  - lidar_year
  - image_name

columns_to_add:
  lidar_unit: dm