
defaults: 
    - _self_
    - model: module.yaml

checkpoint_path: 
verbose: true
rename_rules:
  "^module\\.": ""
  "_bn": ".bn"
  "conv(\\d+)": "conv\\1"

hydra:
  run :
    dir : ${data_dir}/logs
  output_subdir : hydra_logs