root_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data/
data_dir: ${root_dir}/sota/schwartz2025
gdf_path : ${root_dir}/utils/gdf_height_map_initial.geojson

grouping_dates: lidar_acquisition_date
asset_type : height

n_jobs_parrallelized : 3
split : test


hydra:
  run :
    dir : ${data_dir}/logs
  output_subdir : hydra_logs


