_target_: src.datamodule.dataset.get_inputs.s1_s2_timeseries.getS1S2Timeseries
inputs_path: ${data_dir}/sentinel/timeseries/lidarhd/
resolution_input: ${datamodule.dataset.resolution_input}
nb_timeseries_image: 16
nb_timeseries_image_min: 4
nb_acquisition_days_max: null
duplication_level_noise: 0.25
vrts_column: valid_vrts
date_column: lidar_acquisition_date
resampling_method: bilinear
open_even_oob: False