# @package _global_

defaults:
  - override /experiment: d_edsr_utae_sl1_16img
  - override /callbacks: null

seed: 12345 
print_config: true

version_pred_name: geometries_test
project : "sera_predictions"

ckpt_path : /work/work/sera/logs/sera/d_EDSR_UTAE_SL1_16img/v11_d_EDSR_UTAE_SL1_16img/best_checkpoints/epoch_086.ckpt
load_just_weights: True

save_dir: ${log_dir}/${version_pred_name}/predictions

via_bounds : null
via_geojson :
  path : ${data_dir}/utils/change_geometries_120_days_cleaned.geojson
  split: test

datamodule:
  instance: 
    patch_size_input: 64
    patch_size_target: 256


model:
  instance:
    train_metrics: null
    val_metrics: null 
    test_metrics: null
    predictions_save_dir : ${save_dir}