# @package _global_
defaults:
  - override /experiment: edsr_utae_sl1_32img
  - override /callbacks: null
  - override /model/network : ic_End_2_end
  - override /model/network/regression: UTAE
  - override /model/network/super_resolution: EDSR_TS_naive
  - override /datamodule/dataset : change_dataset
  - override /datamodule/dataset/get_inputs : s1_s2_timeseries_change
  - override /datamodule/dataset/method_change : difference_method

seed: 12345 
print_config: true

run_name: ic_d_EDSR_UTAE_SL1_32img

version_pred_name: geometries_test
project : "sera_predictions"

ckpt_path: /work/work/sera/logs/sera/EDSR_UTAE_SL1_32img/v4_EDSR_UTAE_SL1_32img/best_checkpoints/epoch_034.ckpt
load_just_weights: True

save_dir: ${log_dir}/${version_pred_name}/predictions

via_bounds : null
via_geojson :
  path : ${data_dir}/utils/change_geometries_120_days_cleaned.geojson
  split: test

datamodule:
  instance: 
    patch_size_input: 64
    patch_size_target: 256
  dataset:
    input_path: ${data_dir}/sentinel/timeseries/change
    target_path: ${data_dir}/lidar
    geometries_path : ${data_dir}/utils/change_geometries_120_days_cleaned.geojson
    input_resolution : 10
    target_resolution : 2.5
    get_inputs :
      nb_timeseries_image: 32
      duplication_level_noise: 80

logger:
    wandb:
        tags: ["difference map", "super_resolution", "canopy", "EDSR", "UTAE"]

model:
  instance:
    train_metrics: null
    val_metrics: null 
    test_metrics: null
    predictions_save_dir : ${save_dir}
    save_target : False