data_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data
n_jobs: 1

area: chantilly
year_t1: 2022
month_t1: null
day_t1: null # gdf lidar hd 
lidar_unit_t1: "dm" 
year_t2: 2023
month_t2: 09
day_t2: 15 # middle of the month 
lidar_unit_t2: "m"     


# area: landes_v1
# year_t1: 2019
# month_t1: 10
# day_t1: 15 # middle of the month 
# lidar_unit_t1: "m" 
# year_t2: 2021
# month_t2: 03 
# day_t2: 15 # middle of the month 
# lidar_unit_t2: 

# area: landes_v2
# year_t1: 2021
# month_t1: 03
# day_t1: 15 # middle of the month
# lidar_unit_t1: 
# year_t2: 2023
# month_t2: 08
# day_t2: 12 # mean of lidar hd dates
# lidar_unit_t2: 

# area: la_joue_la_fresse
# year_t1: 2019
# month_t1: 06
# day_t1:  15 # middle of the month
# lidar_unit_t1: "m" 
# year_t2: 2022
# month_t2: null
# day_t2: null # gdf lidar hd
# lidar_unit_t2: "dm" 

# area: blois
# year_t1: 2021
# month_t1: 07
# day_t1: 15 # middle of the month 
# lidar_unit_t1: "m" 
# year_t2: 2024
# month_t2: 01
# day_t2: 17 # mean of lidar hd dates 
# lidar_unit_t2: "m" 

# area: vosges
# year_t1: 2020
# month_t1: 03
# day_t1: 01 # middle of march and february give by Martin's paper  
# lidar_unit_t1: "m" 
# year_t2: 2022
# month_t2: null
# day_t2: null # gdf lidar hd 
# lidar_unit_t2: "dm" 


t1:
  initial_lidar_path: ${data_dir}/lidar/uncleaned_lidar/${area}_${year_t1}/
  output_lidar_path: ${data_dir}/lidar/cleaned_lidar/${area}_${year_t1}/
  replace_zero: false
  no_data: "nan"
  # acquisition_date: ${year_t1}${month_t1}${day_t1} # comment this if you want to use gdf lidar hd
  acquisition_date: "gdf_lidar_hd" # uncommment this if you want to use gdf lidar hd
  

t2:
  initial_lidar_path: ${data_dir}/lidar/uncleaned_lidar/${area}_${year_t2}/
  output_lidar_path: ${data_dir}/lidar/cleaned_lidar/${area}_${year_t2}/
  replace_zero: true
  no_data: "nan"
  acquisition_date: ${year_t2}${month_t2}${day_t2} # comment this if you want to use gdf lidar hd
  # acquisition_date: "gdf_lidar_hd" # uncommment this if you want to use gdf lidar hd

tile_size_grouped_tif: 10000 # in meters, e.g. 500 for 500m x 500m tiles
tile_size_geojson: 1000 # in meters, e.g. 500 for 500m x 500m tiles
min_area: 10000 # minimum area in m^2 for a polygon to be considered a valid mask area

resolution_target: 1.5
acquisition_date_gdf_path: ${data_dir}/utils/gdf_height_map_initial.geojson
output_gdf_path: ${data_dir}/lidar/cleaned_lidar/gdf/gdf_height_map_${area}.geojson
min_non_nan_proportion: 0.40 # our patch size is 640mx640m over 1000mx1000m, we want to have at least a non-empty patch
min_non_zero_proportion: 0.40 # our patch size is 640mx640m over 1000mx1000m, we want to have at least a non-empty patch
