root_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data/
data_dir: ${root_dir}/sentinel/timeseries/diff_map

create_vrts: src.preprocessing.datasets.get_clean_dataset_utils.create_vrts_timeseries
get_valid_vrts: src.preprocessing.datasets.get_clean_dataset_utils.get_valid_vrts_timeseries

n_jobs_parrallelized: -1

initial_gdf_path: ${root_dir}/utils/gdf_diff_map_timeseries_t1.geojson
grouping_dates: lidar_acquisition_date_t2
validation_column: valid_vrts_t2
# gdf_clean_path: ${root_dir}/utils/gdf_diff_map_timeseries_t1.geojson
# gdf_unclean_path: ${root_dir}/utils/gdf_diff_map_timeseries_t1_unsaved.geojson
gdf_clean_path: ${data_dir}/gdf_diff_map_timeseries.geojson
gdf_unclean_path: ${data_dir}/gdf_diff_map_timeseries_t2_unsaved.geojson

hydra:
  run :
    dir : ${data_dir}/logs
  output_subdir : hydra_logs