_target_: src.models.networks.regression.open_canopy.OpenCanopyModel
model_class :
  backbone: pvt_v2_b3.in1k
  pretrained: True
  pretrained_path: /work/data/utils/pvt_v2_b3.in1k.bin
  use_FPN: False
  num_channels: 4
  num_classes: 1
  img_size : ${datamodule.instance.patch_size_input}


repo_model : /work/work/Open-canopy
ckpt_path: /work/data/utils/pvtv2.ckpt
