data_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data/sentinel/timeseries/lidarhd
gdf_path : /lustre/fsn1/projects/rech/ego/uof45xi/data/utils/geometries.geojson

grouping_date: lidar_acquisition_date

n_jobs_parrallelized : 5

resolution : 10
tile_shape : 5000
max_tile_size : 10
cloudless_portion : 60
cloud_prb : 40
country : "France"
composite_method_s1 : TIMESERIES
composite_method_s2 : TIMESERIES
duration : 60
s1_orbit : BOTH


