defaults:
  - metrics_calculator : height_map_metrics


forest_mask_path : ${data_dir}/utils/forest_mask.parquet
classification_path : ${data_dir}/lidar_classification/
classes_to_keep : [5]

train_metrics: null

val_metrics:
  _target_: src.module.metrics.masked_forest_metrics.maskedForestMetrics
  metrics_calculator : ${module.metrics.metrics_calculator}
  forest_mask_path : null #forest map is too long to clip, we don't keep for validation  
  classification_path : ${module.metrics.classification_path}
  classes_to_keep : ${module.metrics.classes_to_keep}
  resolution_target : ${datamodule.dataset.resolution_target}

test_metrics:
  _target_: src.module.metrics.masked_forest_metrics.maskedForestMetrics
  metrics_calculator : ${module.metrics.metrics_calculator}
  forest_mask_path : ${module.metrics.forest_mask_path}
  classification_path : ${module.metrics.classification_path}
  classes_to_keep : ${module.metrics.classes_to_keep}
  resolution_target : ${datamodule.dataset.resolution_target}