# @package _global_
defaults:
    - override /module/loss: masked_normalised_huber
    - override /module/regression_model: utae_mf
    - override /module/metrics/metrics_calculator: difference_map_metrics
    - override /datamodule/dataset : change_map_dataset

project: "train_sera"
run_name: d-sera_h
run_version: v1_${run_name}
data_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data
ckpt_path: last

module:
    metrics:
        forest_mask_path: null
        classification_path: null

datamodule:
    instance:
        batch_size: 2
        num_workers: 8
    dataset:
        patch_size_input: 64
        patch_size_target: 256
        get_inputs_t1:
            inputs_path: ${data_dir}/sentinel/timeseries/diff_map/
            valid_column: valid_vrts_t1
            date_column: lidar_acquisition_date_t1
        get_inputs_t2:
            inputs_path: ${data_dir}/sentinel/timeseries/diff_map/
            valid_column: valid_vrts_t2
            date_column: lidar_acquisition_date_t2
        get_targets_t1:
            targets_path: ${data_dir}/lidar/
            date_column: lidar_acquisition_date_t1
            unit_column: lidar_unit_t1
        get_targets_t2:
            targets_path: ${data_dir}/lidar/
            date_column: lidar_acquisition_date_t2
            unit_column: lidar_unit_t2


callbacks:
    log_image_predictions: 
        log_inputs: 
            _target_: src.callbacks.log_images_utils.log_5d_s1_s2_images_revisit
            max_nb_timeseries_input: 5

trainer:
    devices: auto   
    strategy: auto
