# @package _global_

project: "train_sera"
run_name: h-sera_h_max
run_version: v1_${run_name}
data_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data
ckpt_path: last

module:
    metrics:
        forest_mask_path: ${data_dir}/open_canopy/forest_mask.parquet
        classification_path: ${data_dir}/open_canopy/

datamodule:
    instance:
        batch_size: 2
        num_workers: 8
    dataset:
        patch_size_input: 64
        patch_size_target: 256
        train_dataset:
            data_augmentation: False
        get_targets:
            targets_path: ${data_dir}/open_canopy/

trainer:
    devices: auto   
    strategy: auto
