# @package _global_

project: "train_sera"
run_name: h-sera_h_big_patch_08img
run_version: v1_${run_name}
data_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data
ckpt_path: last

module:
    metrics:
        forest_mask_path: ${data_dir}/open_canopy/forest_mask.parquet
        classification_path: ${data_dir}/open_canopy/

datamodule:
    instance:
        batch_size: 4
    
    dataset:
        patch_size_input: 48
        patch_size_target: 192
        get_inputs:
            nb_timeseries_image: 8
        get_targets:
            targets_path: ${data_dir}/open_canopy/

