# @package _global_

defaults:
    - override /module/super_resolution_model: null
    - override /module/regression_model: unet
    - override /datamodule/dataset/get_inputs: s1_s2_composites
    - override /callbacks/image_type: s1_s2_composites

project: "train_sera"
run_name: h-unet
run_version: v2_${run_name}
data_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data
ckpt_path: last

module:
    instance:
        super_resolution_model: null
    metrics:
        forest_mask_path: ${data_dir}/open_canopy/forest_mask.parquet
        classification_path: ${data_dir}/open_canopy/

datamodule:
    dataset:
        gdf_path: ${data_dir}/sentinel/composites/lidarhd/gdf_height_map_composites.geojson
        resolution_input: 2.5
        patch_size_input: 128
        get_targets:
            targets_path: ${data_dir}/open_canopy/


