prepare_images:
  _target_: src.callbacks.log_images_utils.height_map_mode
  min_value_normalization: 0
  max_value_normalization: 40
  colormap: "magma"

log_inputs:
  _target_: src.callbacks.log_images_utils.log_4d_s1_s2_images